// Code generated by mockery. DO NOT EDIT.

package relayerapi

import (
	context "context"

	db "github.com/cosmos/ibc-relayer/db/gen/db"
	mock "github.com/stretchr/testify/mock"
)

// MockRelayerAPIQueries is an autogenerated mock type for the RelayerAPIQueries type
type MockRelayerAPIQueries struct {
	mock.Mock
}

type MockRelayerAPIQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelayerAPIQueries) EXPECT() *MockRelayerAPIQueries_Expecter {
	return &MockRelayerAPIQueries_Expecter{mock: &_m.Mock}
}

// GetRelayRequest provides a mock function with given fields: ctx, arg
func (_m *MockRelayerAPIQueries) GetRelayRequest(ctx context.Context, arg db.GetRelayRequestParams) (db.Ibcv2RelayRequest, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetRelayRequest")
	}

	var r0 db.Ibcv2RelayRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRelayRequestParams) (db.Ibcv2RelayRequest, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetRelayRequestParams) db.Ibcv2RelayRequest); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Ibcv2RelayRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetRelayRequestParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRelayerAPIQueries_GetRelayRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRelayRequest'
type MockRelayerAPIQueries_GetRelayRequest_Call struct {
	*mock.Call
}

// GetRelayRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetRelayRequestParams
func (_e *MockRelayerAPIQueries_Expecter) GetRelayRequest(ctx interface{}, arg interface{}) *MockRelayerAPIQueries_GetRelayRequest_Call {
	return &MockRelayerAPIQueries_GetRelayRequest_Call{Call: _e.mock.On("GetRelayRequest", ctx, arg)}
}

func (_c *MockRelayerAPIQueries_GetRelayRequest_Call) Run(run func(ctx context.Context, arg db.GetRelayRequestParams)) *MockRelayerAPIQueries_GetRelayRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetRelayRequestParams))
	})
	return _c
}

func (_c *MockRelayerAPIQueries_GetRelayRequest_Call) Return(_a0 db.Ibcv2RelayRequest, _a1 error) *MockRelayerAPIQueries_GetRelayRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRelayerAPIQueries_GetRelayRequest_Call) RunAndReturn(run func(context.Context, db.GetRelayRequestParams) (db.Ibcv2RelayRequest, error)) *MockRelayerAPIQueries_GetRelayRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransfersBySourceTx provides a mock function with given fields: ctx, arg
func (_m *MockRelayerAPIQueries) GetTransfersBySourceTx(ctx context.Context, arg db.GetTransfersBySourceTxParams) ([]db.Ibcv2Transfer, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetTransfersBySourceTx")
	}

	var r0 []db.Ibcv2Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.GetTransfersBySourceTxParams) ([]db.Ibcv2Transfer, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.GetTransfersBySourceTxParams) []db.Ibcv2Transfer); ok {
		r0 = rf(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Ibcv2Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.GetTransfersBySourceTxParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRelayerAPIQueries_GetTransfersBySourceTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransfersBySourceTx'
type MockRelayerAPIQueries_GetTransfersBySourceTx_Call struct {
	*mock.Call
}

// GetTransfersBySourceTx is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.GetTransfersBySourceTxParams
func (_e *MockRelayerAPIQueries_Expecter) GetTransfersBySourceTx(ctx interface{}, arg interface{}) *MockRelayerAPIQueries_GetTransfersBySourceTx_Call {
	return &MockRelayerAPIQueries_GetTransfersBySourceTx_Call{Call: _e.mock.On("GetTransfersBySourceTx", ctx, arg)}
}

func (_c *MockRelayerAPIQueries_GetTransfersBySourceTx_Call) Run(run func(ctx context.Context, arg db.GetTransfersBySourceTxParams)) *MockRelayerAPIQueries_GetTransfersBySourceTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.GetTransfersBySourceTxParams))
	})
	return _c
}

func (_c *MockRelayerAPIQueries_GetTransfersBySourceTx_Call) Return(_a0 []db.Ibcv2Transfer, _a1 error) *MockRelayerAPIQueries_GetTransfersBySourceTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRelayerAPIQueries_GetTransfersBySourceTx_Call) RunAndReturn(run func(context.Context, db.GetTransfersBySourceTxParams) ([]db.Ibcv2Transfer, error)) *MockRelayerAPIQueries_GetTransfersBySourceTx_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIBCV2Transfer provides a mock function with given fields: ctx, arg
func (_m *MockRelayerAPIQueries) InsertIBCV2Transfer(ctx context.Context, arg db.InsertIBCV2TransferParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertIBCV2Transfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.InsertIBCV2TransferParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRelayerAPIQueries_InsertIBCV2Transfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIBCV2Transfer'
type MockRelayerAPIQueries_InsertIBCV2Transfer_Call struct {
	*mock.Call
}

// InsertIBCV2Transfer is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertIBCV2TransferParams
func (_e *MockRelayerAPIQueries_Expecter) InsertIBCV2Transfer(ctx interface{}, arg interface{}) *MockRelayerAPIQueries_InsertIBCV2Transfer_Call {
	return &MockRelayerAPIQueries_InsertIBCV2Transfer_Call{Call: _e.mock.On("InsertIBCV2Transfer", ctx, arg)}
}

func (_c *MockRelayerAPIQueries_InsertIBCV2Transfer_Call) Run(run func(ctx context.Context, arg db.InsertIBCV2TransferParams)) *MockRelayerAPIQueries_InsertIBCV2Transfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.InsertIBCV2TransferParams))
	})
	return _c
}

func (_c *MockRelayerAPIQueries_InsertIBCV2Transfer_Call) Return(_a0 error) *MockRelayerAPIQueries_InsertIBCV2Transfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRelayerAPIQueries_InsertIBCV2Transfer_Call) RunAndReturn(run func(context.Context, db.InsertIBCV2TransferParams) error) *MockRelayerAPIQueries_InsertIBCV2Transfer_Call {
	_c.Call.Return(run)
	return _c
}

// InsertRelayRequest provides a mock function with given fields: ctx, arg
func (_m *MockRelayerAPIQueries) InsertRelayRequest(ctx context.Context, arg db.InsertRelayRequestParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertRelayRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.InsertRelayRequestParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRelayerAPIQueries_InsertRelayRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertRelayRequest'
type MockRelayerAPIQueries_InsertRelayRequest_Call struct {
	*mock.Call
}

// InsertRelayRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertRelayRequestParams
func (_e *MockRelayerAPIQueries_Expecter) InsertRelayRequest(ctx interface{}, arg interface{}) *MockRelayerAPIQueries_InsertRelayRequest_Call {
	return &MockRelayerAPIQueries_InsertRelayRequest_Call{Call: _e.mock.On("InsertRelayRequest", ctx, arg)}
}

func (_c *MockRelayerAPIQueries_InsertRelayRequest_Call) Run(run func(ctx context.Context, arg db.InsertRelayRequestParams)) *MockRelayerAPIQueries_InsertRelayRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.InsertRelayRequestParams))
	})
	return _c
}

func (_c *MockRelayerAPIQueries_InsertRelayRequest_Call) Return(_a0 error) *MockRelayerAPIQueries_InsertRelayRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRelayerAPIQueries_InsertRelayRequest_Call) RunAndReturn(run func(context.Context, db.InsertRelayRequestParams) error) *MockRelayerAPIQueries_InsertRelayRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRelayerAPIQueries creates a new instance of MockRelayerAPIQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelayerAPIQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelayerAPIQueries {
	mock := &MockRelayerAPIQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
